### ISSUE TITLE
Using Http on all connections causes some to fail

### ISSUE THREAD

**Issue by BoogieMonster1O1** [acmpesuecc/pinger#1]
Entering a URL that only accepts https connections will cause the program to throw an exception.

Stacktrace:
```
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 501 for URL: http://repo1.maven.org
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at pinger.Pinger.main(Pinger.java:17)
```

Affecting code: https://github.com/BoogieMonster1O1/pinger/blob/master/src/main/java/pinger/Pinger.java#L14

**Comment by BoogieMonster1O1** [comment]
A suggested approach would be to accept some user input on weather https should be used in the connection, and depending on what was inputted, the resulting url should be modified accordingly.

**Comment by sreechand2002** [comment]
hello @BoogieMonster1O1 when i implement this , should i remove the instanceof check?
